version: '3.8'

services:
  backend:
    build: .
    container_name: content_studio_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data/articles.db
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: .
    container_name: content_studio_frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  data:
    driver: local

